/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.admin;

import DAO.ChucVuDAO;
import DAO.HopDongLaoDongDAO;
import DAO.LuongDAO;
import DAO.NhanVienDAO;
import DAO.PhongBanDAO;
import DAO.TrinhDoHocVanDAO;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.ChucVu;
import model.HopDongLaoDong;
import model.NhanVien;

/**
 *
 * @author admin
 */
public class CapNhatNhanVien extends javax.swing.JPanel {

    private ArrayList<NhanVien> dataList;
    private DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

    /**
     */
    public CapNhatNhanVien() {
        initComponents();
        dataList = NhanVienDAO.getDS();
        loadNVComboBox();
        loadDuLieuNV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        maNvTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hoTenTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        danTocTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        gioiTinh = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        queQuanTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ngaySinhTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        soDTTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        chucVu = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        phongBan = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        bacLuong = new javax.swing.JComboBox<>();
        updateBtn = new javax.swing.JButton();
        trinhDo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        chuyenNganh = new javax.swing.JComboBox<>();
        chonNV = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();

        title.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("CẬP NHẬT THÔNG TIN NHÂN VIÊN");

        maNvTxt.setEditable(false);
        maNvTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maNvTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã NV");

        jLabel2.setText("Họ tên");

        hoTenTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoTenTxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Dân tộc");

        jLabel4.setText("Giới tính");

        gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        gioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gioiTinhActionPerformed(evt);
            }
        });

        jLabel5.setText("Quê quán");

        queQuanTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queQuanTxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Ngày sinh");

        ngaySinhTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngaySinhTxtActionPerformed(evt);
            }
        });

        jLabel7.setText("Số ĐT");

        jLabel8.setText("Chức vụ");

        chucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhân viên bán hàng", "Trợ lý", "Kế toán", "Lập trình viên", "Quản lý dự án", "Trưởng phòng", "Phó giám đốc", "Giám đốc" }));
        chucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chucVuActionPerformed(evt);
            }
        });

        jLabel9.setText("Phòng ban");

        phongBan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng Nhân Sự", "Phòng Tài Chính", "Phòng Kế Toán", "Phòng Kinh Doanh", "Phòng Kỹ Thuật", "Phòng Hành Chính" }));

        jLabel10.setText("Trình độ");

        jLabel11.setText("Bậc Lương");

        bacLuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bậc 1", "Bậc 2", "Bậc 3", "Bậc 4", "Bậc 5" }));

        updateBtn.setBackground(new java.awt.Color(0, 204, 0));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Cập nhật");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        trinhDo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cao đẳng", "Cử nhân", "Thạc sĩ", "Tiến sĩ" }));
        trinhDo.setEnabled(false);

        jLabel12.setText("Chuyên ngành");

        chuyenNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kỹ thuật", "Quản trị kinh doanh", "Công nghệ thông tin", "Kinh tế đối ngoại", "Kế toán", "Luật kinh tế", "Marketing" }));
        chuyenNganh.setEnabled(false);

        chonNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonNVActionPerformed(evt);
            }
        });

        jLabel16.setText("Nhân viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(updateBtn)
                .addGap(391, 391, 391))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel16)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chonNV, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hoTenTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(maNvTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(danTocTxt)
                            .addComponent(queQuanTxt)
                            .addComponent(ngaySinhTxt)
                            .addComponent(soDTTxt))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chucVu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phongBan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bacLuong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(trinhDo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chuyenNganh, 0, 230, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(222, 222, 222))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chonNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(hoTenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(danTocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(maNvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(queQuanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(trinhDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngaySinhTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel12)
                    .addComponent(chuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soDTTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11)
                    .addComponent(bacLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(updateBtn)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void maNvTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maNvTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maNvTxtActionPerformed

    private void queQuanTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queQuanTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_queQuanTxtActionPerformed

    private void ngaySinhTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngaySinhTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngaySinhTxtActionPerformed

    private void chucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chucVuActionPerformed

    private void gioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gioiTinhActionPerformed

    private void hoTenTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoTenTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoTenTxtActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

        String maNV = maNvTxt.getText();
        String hoTen = hoTenTxt.getText();
        String danToc = danTocTxt.getText();
        String gt = gioiTinh.getSelectedItem().toString();
        String queQuan = queQuanTxt.getText();
        String ns = ngaySinhTxt.getText();
        String sdt = soDTTxt.getText();
        String cv = chucVu.getSelectedItem().toString();
        String pb = phongBan.getSelectedItem().toString();
        String tenTD = trinhDo.getSelectedItem().toString();
        String tenCN = chuyenNganh.getSelectedItem().toString();
        
        String luong = bacLuong.getSelectedItem().toString();
        NhanVien nv = new NhanVien(maNV, hoTen, danToc, gt, queQuan, ns, sdt, ChucVuDAO.getCV(cv), PhongBanDAO.getPhongBan(pb), TrinhDoHocVanDAO.getTDHV(tenTD, tenCN), LuongDAO.getLuong(luong));
        NhanVienDAO.updateNV(nv);
        JOptionPane.showMessageDialog(this, "Sửa thông tin nhân viên thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void chonNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonNVActionPerformed
        // TODO add your handling code here:
        loadDuLieuNV();
    }//GEN-LAST:event_chonNVActionPerformed

    public void loadDuLieuNV() {
        String maNVChon = this.chonNV.getSelectedItem().toString();
        for (NhanVien nv : this.dataList) {
            if (nv.getMaNV().equals(maNVChon)) {
                maNvTxt.setText(nv.getMaNV());
                hoTenTxt.setText(nv.getHoTen());
                danTocTxt.setText(nv.getDanToc());
                queQuanTxt.setText(nv.getQueQuan());
                ngaySinhTxt.setText(nv.getNgaySinh());
                soDTTxt.setText(nv.getSoDT());
                chucVu.setSelectedItem(nv.getChucVu().getTenCV());
                phongBan.setSelectedItem(nv.getPhongBan().getTenPB());
                gioiTinh.setSelectedItem(nv.getGioiTinh());
                trinhDo.setSelectedItem(nv.getTrinhDo().getTenTD());
                chuyenNganh.setSelectedItem(nv.getTrinhDo().getcNganh());
                bacLuong.setSelectedItem(nv.getBacLuong().getBacLuong());
            }
        }
    }

    public void loadNVComboBox() {
        for (NhanVien nv : this.dataList) {
            model.addElement(nv.getMaNV());
        }
        chonNV.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bacLuong;
    private javax.swing.JComboBox<String> chonNV;
    private javax.swing.JComboBox<String> chucVu;
    private javax.swing.JComboBox<String> chuyenNganh;
    private javax.swing.JTextField danTocTxt;
    private javax.swing.JComboBox<String> gioiTinh;
    private javax.swing.JTextField hoTenTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField maNvTxt;
    private javax.swing.JTextField ngaySinhTxt;
    private javax.swing.JComboBox<String> phongBan;
    private javax.swing.JTextField queQuanTxt;
    private javax.swing.JTextField soDTTxt;
    private javax.swing.JLabel title;
    private javax.swing.JComboBox<String> trinhDo;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
