/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.admin;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import DAO.NhanVienDAO;
import model.NhanVien;

/**
 *
 * @author admin
 */
public class DanhSachNhanVien extends javax.swing.JPanel {

    private static String dataColumn[] = {"Mã NV", "Họ tên", "Dân tộc", "Giới tính", "Quê quán", "Ngày sinh", "SĐT"};
    private DefaultTableModel tableDsNvModel;

    /**
     * Creates new form DanhSachNhanVien
     */
    public DanhSachNhanVien() {
        initComponents();
        hienThiDuLieuNV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsNhanVien = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH NHÂN VIÊN");
        jLabel1.setToolTipText("");

        dsNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(dsNhanVien);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void hienThiDuLieuNV() {
        ArrayList<NhanVien> dataNV = NhanVienDAO.getDS();
        int soNV = dataNV.size();
        Object[][] data = new Object[soNV][];
        for (int i = 0; i < soNV; i++) {

            Object[] rowData = new Object[]{dataNV.get(i).getMaNV(), dataNV.get(i).getHoTen(), dataNV.get(i).getDanToc(), dataNV.get(i).getGioiTinh(), dataNV.get(i).getQueQuan(), dataNV.get(i).getNgaySinh(), dataNV.get(i).getSoDT()};
            data[i] = rowData;
        }
        
        tableDsNvModel = new DefaultTableModel(data, dataColumn);
        dsNhanVien.setModel(tableDsNvModel);
    }

    public void setTableNvModel(DefaultTableModel md) {
        this.tableDsNvModel = md;
    }
    public DefaultTableModel getTableNvModel() {
        return this.tableDsNvModel;
    }
    public javax.swing.JTable getDsNhanVien() {
        return this.dsNhanVien;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dsNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
