/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.user;

import view.admin.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import DAO.NhanVienDAO;
import javax.swing.JOptionPane;
import model.NhanVien;
import utils.LoadDuLieuTable;

/**
 *
 * @author admin
 */
public class DanhSachNhanVien extends javax.swing.JPanel {

    private static String dataColumn[] = {"Mã NV", "Họ tên", "Dân tộc", "Giới tính", "Quê quán", "Ngày sinh", "SĐT", "Chức vụ", "Phòng ban"};
    private DefaultTableModel tableDsNvModel;
    private ArrayList<NhanVien> dataList;

    /**
     * Creates new form DanhSachNhanVien
     */
    public DanhSachNhanVien() {
        initComponents();
        dataList = NhanVienDAO.getDS();
        hienThiDuLieuNV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dsNhanVien = new javax.swing.JTable();
        refreshBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH NHÂN VIÊN");
        jLabel1.setToolTipText("");

        dsNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(dsNhanVien);

        refreshBtn.setText("Tải lại");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(refreshBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        this.dataList = NhanVienDAO.getDS();
        this.hienThiDuLieuNV();
    }//GEN-LAST:event_refreshBtnActionPerformed

    public void hienThiDuLieuNV() {
        Object[][] data = LoadDuLieuTable.chuyenArrayListSangObj(dataList);

        tableDsNvModel = new DefaultTableModel(data, dataColumn);
        dsNhanVien.setModel(tableDsNvModel);
    }

    public void setTableNvModel(DefaultTableModel md) {
        this.tableDsNvModel = md;
    }

    public DefaultTableModel getTableNvModel() {
        return this.tableDsNvModel;
    }

    public javax.swing.JTable getDsNhanVien() {
        return this.dsNhanVien;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dsNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
