/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.user;

import DAO.ChamCongTongHopDAO;
import DAO.NhanVienDAO;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;
import model.TaiKhoan;
import utils.LoadDuLieuTable;

/**
 *
 * @author admin
 */
public class ThongTinNhanVien extends javax.swing.JPanel {

    private ArrayList<NhanVien> dataList;
    private TaiKhoan taiKhoan;
    private static String dataColumn[] = {"STT", "Tháng", "Năm", "Ngày LV", "Số SP", "Lương Tháng"};
    private DefaultTableModel tableLuongModel;
    private ArrayList<Object[]> dataLuong;
    /**
     */
    public ThongTinNhanVien(TaiKhoan tk) {
        this.taiKhoan = tk;
        initComponents();
        dataList = NhanVienDAO.getDS();
        loadDuLieuNV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maNvTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hoTenTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        danTocTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        queQuanTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ngaySinhTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        soDTTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangLuong = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        thangCB = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        namCB = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        phongBan = new javax.swing.JTextField();
        xemLuongBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        chucVu = new javax.swing.JTextField();

        maNvTxt.setEditable(false);
        maNvTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maNvTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Mã NV");

        jLabel2.setText("Họ tên");

        hoTenTxt.setEditable(false);
        hoTenTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoTenTxtActionPerformed(evt);
            }
        });

        jLabel3.setText("Dân tộc");

        danTocTxt.setEditable(false);

        jLabel5.setText("Quê quán");

        queQuanTxt.setEditable(false);
        queQuanTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queQuanTxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Ngày sinh");

        ngaySinhTxt.setEditable(false);
        ngaySinhTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngaySinhTxtActionPerformed(evt);
            }
        });

        jLabel7.setText("Số ĐT");

        soDTTxt.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("THÔNG TIN NHÂN VIÊN");

        bangLuong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tháng", "Năm", "Ngày LV", "Số SP", "Lương Tháng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bangLuong);
        if (bangLuong.getColumnModel().getColumnCount() > 0) {
            bangLuong.getColumnModel().getColumn(0).setResizable(false);
            bangLuong.getColumnModel().getColumn(1).setResizable(false);
            bangLuong.getColumnModel().getColumn(2).setResizable(false);
            bangLuong.getColumnModel().getColumn(3).setResizable(false);
            bangLuong.getColumnModel().getColumn(4).setResizable(false);
            bangLuong.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("BẢNG LƯƠNG");

        thangCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel8.setText("Tháng");

        jLabel9.setText("Năm");

        namCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));

        jLabel10.setText("Phòng ban");

        phongBan.setEditable(false);

        xemLuongBtn.setText("Xem lương");
        xemLuongBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemLuongBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Chức vụ");

        chucVu.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(61, 61, 61)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(hoTenTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                .addComponent(maNvTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(danTocTxt)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel10)
                                .addComponent(jLabel5)
                                .addComponent(jLabel11))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(soDTTxt)
                                        .addComponent(ngaySinhTxt)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(chucVu, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))))
                        .addComponent(phongBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(queQuanTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(30, 30, 30)
                                .addComponent(thangCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel9)
                                .addGap(28, 28, 28)
                                .addComponent(namCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(xemLuongBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thangCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(namCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xemLuongBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(hoTenTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(maNvTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(danTocTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(queQuanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(ngaySinhTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(soDTTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(phongBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void maNvTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maNvTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maNvTxtActionPerformed

    private void queQuanTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queQuanTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_queQuanTxtActionPerformed

    private void ngaySinhTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngaySinhTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngaySinhTxtActionPerformed

    private void hoTenTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoTenTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoTenTxtActionPerformed

    private void xemLuongBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemLuongBtnActionPerformed
        String thang = thangCB.getSelectedItem().toString();
        String nam = namCB.getSelectedItem().toString();
        
        dataLuong = ChamCongTongHopDAO.getBangLuongNV(taiKhoan.getNv().getMaNV(), thang, nam);
        Object data[][] = LoadDuLieuTable.loadDuLieuBangLuong(dataLuong);
        
        tableLuongModel = new DefaultTableModel(data, dataColumn);
        bangLuong.setModel(tableLuongModel);
    }//GEN-LAST:event_xemLuongBtnActionPerformed

    public void loadDuLieuNV() {
        NhanVien nv = taiKhoan.getNv();
        maNvTxt.setText(nv.getMaNV());
        hoTenTxt.setText(nv.getHoTen());
        danTocTxt.setText(nv.getDanToc());
        queQuanTxt.setText(nv.getQueQuan());
        ngaySinhTxt.setText(nv.getNgaySinh());
        soDTTxt.setText(nv.getSoDT());
        phongBan.setText(nv.getPhongBan().getTenPB());
        chucVu.setText(nv.getChucVu().getTenCV());
    }

    public void setTaiKhoan(TaiKhoan tk) {
        this.taiKhoan = tk;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangLuong;
    private javax.swing.JTextField chucVu;
    private javax.swing.JTextField danTocTxt;
    private javax.swing.JTextField hoTenTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maNvTxt;
    private javax.swing.JComboBox<String> namCB;
    private javax.swing.JTextField ngaySinhTxt;
    private javax.swing.JTextField phongBan;
    private javax.swing.JTextField queQuanTxt;
    private javax.swing.JTextField soDTTxt;
    private javax.swing.JComboBox<String> thangCB;
    private javax.swing.JButton xemLuongBtn;
    // End of variables declaration//GEN-END:variables
}
